steps:

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sample-fastapi-container:v2', '.' ]
  id: docker build

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/sample-fastapi-container:v2' ]
  id: docker push

- name: 'gcr.io/$PROJECT_ID/sample-fastapi-container:v2'
  args: [ 'pytest' ]
  id: test
